version: '3'

services:
  hello-api:
#    image: your image
    environment:
      - TZ=Asia/Shanghai
    privileged: true
    volumes:
      - ./etc:/app/etc
    ports:
      - "8888:8888"
    stdin_open: true
    tty: true
